### ISSUE TITLE
_Forest::__generate_graph() 复杂度较高

### ISSUE THREAD

**Issue by bandiaoz** [ChuTian-SCPC/ACM-generator#12]
生成森林的 `_Forest::__generate_graph()` 函数中，我理解的是根据 `_trees_size` 来生成森林，每个树的大小由 `_trees_size` 决定，会先生成每个树，然后再依次不添加额外边地将每个树合并在 `result_graph` 中。但是连接两个大小为 `x` 和 `y` 的树，复杂度为 `O(x + y)`，这样如果森林由很多棵比较小的树组成复杂度会达到平方级别。

**Comment by ChuTian-SCPC** [comment]
看起来是的，你有什么解决思路吗？

**Comment by ChuTian-SCPC** [comment]
`merge`和`link`的设计初衷是想到有一些树/图可以通过“组装”的方式得到，本身期望它能够更“优雅”地生成`Forest`和`FlowerChain`。但是目前看起来事与愿违。
目前考虑到两种解决方式：
1. `_Forest::__generator_graph()`不再调用`_LinkImpl`去将边组合起来。直接拿到生成的树的边即可，这是最简单的修改方法。
2. 让`Tree`和`Graph`能够支持`merge`/`link`的操作，将每次合并的复杂度降为 $O(y)$ 。

**Comment by bandiaoz** [comment]
`LinkType` 中 `Direct` 和 `Increase`是似乎是可以做到 $O(y)$ 复杂度合并的，类似于将`_LinkImpl(TG1<NodeType, EdgeType> source1, TG2<NodeType, EdgeType> source2, int extra_edge_count, LinkType link_type) `函数的第一个参数使用引用类型，所有操作都在 `source1` 的基础上进行，但是例如 `__judge_limits()` 等操作可能难以实现。
我认为在 `_Forest::__generator_graph()` 等内置方法中不使用 `_LinkImpl` 而直接使用朴素的方法是可以接受的，`_LinkImpl` 依旧可以在写 `gen.cpp` 时针对题目很方便的手动构造出特殊的图。

**Comment by bandiaoz** [comment]
`LinkType` 中 `Direct` 和 `Increase` 是似乎是可以做到  $O(y)$ 复杂度合并的，类似于将 `_LinkImpl(TG1<NodeType, EdgeType> source1, TG2<NodeType, EdgeType> source2, int extra_edge_count, LinkType link_type)` 函数的第一个参数使用引用类型，所有操作都在 `source1` 的基础上进行，但是例如 `__judge_limits()` 等操作可能难以实现。
我认为在 `_Forest::__generator_graph()` 等内置方法中不使用 `_LinkImpl` 而直接使用朴素的方法是可以接受的，`_LinkImpl` 依旧可以在写 `gen.cpp` 时，针对题目很方便的手动构造出特殊的图。

**Comment by ChuTian-SCPC** [comment]
sounds good!
十分感谢！
那么目前的解决方案就是将`_Forest::__generator_graph()`更改成简单的方法。

**Comment by ChuTian-SCPC** [comment]
@bandiaoz pr已经修改了生成方式，你可以看一下是否还存在问题。

**Comment by bandiaoz** [comment]
没有问题了
