### ISSUE TITLE
_Tree 和 _Graph 中 default_output 函数输出点权的那一行最后多了空格，无法通过 val。

### ISSUE THREAD

**Issue by bandiaoz** [ChuTian-SCPC/ACM-generator#15]
```cpp
    /**
     * @brief 生成树的默认输出函数
     * @note `first_line` 为 `node_count` 和 `root` 的输出
     *        接下来一行输出点权，之后输出每条边的信息
     */
    void default_output(std::ostream& os) const {
        std::vector<int> first_line_vec;
        if (_output_node_count) {
            first_line_vec.push_back(_node_count);
        }
        if (_is_rooted && _output_root) {
            first_line_vec.push_back(root());
        }
        std::string first_line = join(first_line_vec);
        std::string second_line;
        if constexpr (!std::is_void<NodeType>::value) {
            second_line = join(_nodes_weight);
        }
        std::vector<std::string> output_lines{first_line, second_line};
        output_lines.erase(std::remove(output_lines.begin(), output_lines.end(), ""), output_lines.end());
        os << join(output_lines, "\n");
        if (_node_count > 1) {
            os << "\n";
        }

        int edge_cnt = 0;
        std::vector<_Edge<EdgeType>> output_edges = __get_output_edges();
        for (_Edge<EdgeType> e: output_edges) {
            if (_swap_node && rand_numeric::rand_bool()) {
                e.set_output_default(true);
            }
            os << e;
            e.set_output_default();
            if (++edge_cnt < _node_count - 1) {
                os << "\n";
            }
        }
    }

    /**
     * @brief 图的默认输出函数
     * @note 第一行输出 `_node_count` 和 `_edge_count`
     *       接下来一行输出点权，之后输出每条边的信息
     */
    void default_output(std::ostream& os) const {
        std::vector<int> first_line_vec;
        if (_output_node_count) {
            first_line_vec.push_back(_node_count);
        }
        if (_output_edge_count) {
            first_line_vec.push_back(_edge_count);
        }
        std::string first_line = join(first_line_vec);
        std::string second_line;
        if constexpr (!std::is_void<NodeType>::value) {
            second_line = join(_nodes_weight);
        }
        std::vector<std::string> output_lines{first_line, second_line};
        output_lines.erase(std::remove(output_lines.begin(), output_lines.end(), ""), output_lines.end());
        os << join(output_lines, "\n");
        if (_edge_count >= 1) {
            os << "\n";
        }
        
        int edge_cnt = 0;
        for (_Edge<EdgeType> e: __get_output_edges()) {
            if (_swap_node && rand_numeric::rand_bool()) {
                e.set_output_default(true);
            }
            os << e;
            e.set_output_default();
            if (++edge_cnt < _edge_count) {
                os << "\n";
            }
        }
    }
```
我的写法使用了 `testlib` 中的 `join` 函数，简化了部分代码，同时删除了 `__output_node_weights()` 函数

**Comment by ChuTian-SCPC** [comment]
> ```c++
>     /**
>      * @brief 生成树的默认输出函数
>      * @note `first_line` 为 `node_count` 和 `root` 的输出
>      *        接下来一行输出点权，之后输出每条边的信息
>      */
>     void default_output(std::ostream& os) const {
>         std::vector<int> first_line_vec;
>         if (_output_node_count) {
>             first_line_vec.push_back(_node_count);
>         }
>         if (_is_rooted && _output_root) {
>             first_line_vec.push_back(root());
>         }
>         std::string first_line = join(first_line_vec);
>         std::string second_line;
>         if constexpr (!std::is_void<NodeType>::value) {
>             second_line = join(_nodes_weight);
>         }
>         std::vector<std::string> output_lines{first_line, second_line};
>         output_lines.erase(std::remove(output_lines.begin(), output_lines.end(), ""), output_lines.end());
>         os << join(output_lines, "\n");
>         if (_node_count > 1) {
>             os << "\n";
>         }
> 
>         int edge_cnt = 0;
>         std::vector<_Edge<EdgeType>> output_edges = __get_output_edges();
>         for (_Edge<EdgeType> e: output_edges) {
>             if (_swap_node && rand_numeric::rand_bool()) {
>                 e.set_output_default(true);
>             }
>             os << e;
>             e.set_output_default();
>             if (++edge_cnt < _node_count - 1) {
>                 os << "\n";
>             }
>         }
>     }
> 
>     /**
>      * @brief 图的默认输出函数
>      * @note 第一行输出 `_node_count` 和 `_edge_count`
>      *       接下来一行输出点权，之后输出每条边的信息
>      */
>     void default_output(std::ostream& os) const {
>         std::vector<int> first_line_vec;
>         if (_output_node_count) {
>             first_line_vec.push_back(_node_count);
>         }
>         if (_output_edge_count) {
>             first_line_vec.push_back(_edge_count);
>         }
>         std::string first_line = join(first_line_vec);
>         std::string second_line;
>         if constexpr (!std::is_void<NodeType>::value) {
>             second_line = join(_nodes_weight);
>         }
>         std::vector<std::string> output_lines{first_line, second_line};
>         output_lines.erase(std::remove(output_lines.begin(), output_lines.end(), ""), output_lines.end());
>         os << join(output_lines, "\n");
>         if (_edge_count >= 1) {
>             os << "\n";
>         }
>         
>         int edge_cnt = 0;
>         for (_Edge<EdgeType> e: __get_output_edges()) {
>             if (_swap_node && rand_numeric::rand_bool()) {
>                 e.set_output_default(true);
>             }
>             os << e;
>             e.set_output_default();
>             if (++edge_cnt < _edge_count) {
>                 os << "\n";
>             }
>         }
>     }
> ```
> 
> 我的写法使用了 `testlib` 中的 `join` 函数，简化了部分代码，同时删除了 `__output_node_weights()` 函数

感谢您的反馈！
如果您愿意的话，可以提交pr。

**Comment by bandiaoz** [comment]
提交了，你可以测试看看。

**Comment by ChuTian-SCPC** [comment]
感谢您的贡献。
pr已经merge。
