### ISSUE TITLE
路径求助

### ISSUE THREAD

**Issue by merlin02306** [ChuTian-SCPC/ACM-generator#9]
如何获取当前路径？
Path a; 
a.path();
显示空路径。传入windows路径，斜杠前面加转义，说是非法，不知如何使用。

**Comment by ChuTian-SCPC** [comment]
当前路径用 Path a(".");就行了。

**Comment by ChuTian-SCPC** [comment]
如果还有问题请更详细的描述，如果没有问题该issue将在24小时后关闭

> 如何获取当前路径？ Path a; a.path(); 显示空路径。传入windows路径，斜杠前面加转义，说是非法，不知如何使用。

**Comment by merlin02306** [comment]
自己测了一下，中文路径的缘故

**Comment by merlin02306** [comment]
给英文路径，能初始化路径了。Path a(".");    cout<<a.path();  只打印出了'.'，没有当前路径。

**Comment by ChuTian-SCPC** [comment]
.就是表示当前路径，如果你想显示出当前路径，可以
```cpp
Path a(".");
a.full();
cout<<a.path()<<endl;
```

**Comment by ChuTian-SCPC** [comment]
> 自己测了一下，中文路径的缘故

不借助第三方库或者高版本的话，要支持看起来并不容易，目前暂时没有支持的计划。
